### PR TITLE
dsn_patch_2

### PR DESCRIPTION
**Pull request by shoc71**
dsn_class.py
- added licorice_black (didn't seem to be there before)

dsn_levels.py
- slightly adjusted the menuscene text "hit space..." to go down a little not to overlap with the pngs

main.py
- added caption and icon functions (icon isn't working so a separate issue shall be opened for that)

assests/images
- 5 images of the purple player icon have been uploaded in folder (easier to remove later) / testing to see which one looked best

### CODE REVIEW

**Comment by shoc71** [comment]
probably in the patch, I will put the squares in a proper 128x128 pixel size to remove any background transparency and then try to shrink the little dude

**Comment by slysnivy** [comment]
dsn_class had licorice black in it's code already. That's why when you press on it's commit and look at files changed, dsn_class isn't there. Otherwise it looks fine

**Review by slysnivy — COMMENTED** [review]
dsn_class had licorice black in it's code already. That's why when you press on it's commit and look at files changed, dsn_class isn't there. Otherwise it looks fine

**Comment by shoc71** [comment]
it's all good now so we won't have to worry about it

**Pull request merged**
