### PR TITLE
Delete ideas.txt

### PR DESCRIPTION
**Pull request by shoc71**
- this does not belong here. I have this saved and will upload it somewhere else in this repository

### CODE REVIEW

**Comment by shoc71** [comment]
I will drop this in patch notes once this is approved of

**Comment by slysnivy** [comment]
we should make a folder for these then, just so it doesn't conflict with our main scripts

**Comment by shoc71** [comment]
a seperate folder for future ideas? where would put that in? assets or patch-notes? or have its own thing near the main.py... cuz my thought process it that it should only be dsn py programs with folders on the side

if there is a better place or way of storing it, lemme know cuz for now this is what i think is the best solution

**Comment by slysnivy** [comment]
maybe you're right, it might be better to store this not on github and with our programs

**Comment by shoc71** [comment]
that's genius, let's leave it in the code as commented to-do list that we might want to complete in the future

**Comment by slysnivy** [comment]
we can leave it as the todo comments in certain areas of the code that we need to work on 👍

**Pull request merged**
