### PR TITLE
D-word-file-only

### PR DESCRIPTION
**Pull request by shoc71**

### CODE REVIEW

**Comment by shoc71** [comment]
rename the file, when you download I forgot to do that here

**Comment by slysnivy** [comment]
@shoc71 I thought we were going to use whole words. Do we want it to be individual letters?

**Comment by shoc71** [comment]
we are, well... I lost the file when I saved it and couldn't find for a like some time. Imma re-do it. This is here just in case we want to do something more fancy

**Comment by slysnivy** [comment]
I understand 👍

**Pull request merged**
