### PR TITLE
Testing PR multiple commits

### PR DESCRIPTION
**Pull request by shoc71**

### CODE REVIEW

**Comment by shoc71** [comment]
This totally works. Make your own branch, and use an updated version for patching things up so things are far easier to do an address before.

**Comment by shoc71** [comment]
The question is, which version number should we start from? Or we do start over again from scratch?

**Comment by slysnivy** [comment]
@shoc71 Yea, I thought this would be a problem if we're not updating all 3 files at once. A good work around would be to mention the description and version changed for each file in the pull request. Then once the pull request is merged, then the changes mentioned can be copied and pasted into the updates.txt

**Comment by slysnivy** [comment]
Here's an example description:

dsn_class v.0.2.6:
- Added the color "LICORICE_BLACK" 

dsn_levels v.0.3.4:
- Added the color "LICORICE_BLACK"

**Review by slysnivy — APPROVED** [review]

**Comment by slysnivy** [comment]
@shoc71 Also the branch name should be shorter too

**Comment by shoc71** [comment]
@slysnivy oh I totally agree with what you were saying. I was testing these things to one make sure it works and two make the change minimal to identify how things would transpire in the future.

**Comment by shoc71** [comment]
@slysnivy let's keep this in the back of our minds for now.

**Comment by shoc71** [comment]
@slysnivy also do you think it's safe to delete already merged PR? Or should we keep as a version of our history (like the last 5 are allowed to be kept and everything before is kept)

**Comment by slysnivy** [comment]
Let's keep them

**Pull request merged**
