### PR TITLE
Updates.txt - levels.txt (v.0.5.4)

### PR DESCRIPTION
**Pull request by shoc71**
dsn_class (v.0.3.5)
dsn_levels (v.0.4.2)
main (v.0.2.5)
levels.txt (v.0.5.4) <-- changes the most frequently so using this as the new reference point for changes

### CODE REVIEW

**Review by slysnivy — CHANGES_REQUESTED** [review]
I think the "incorrectly labelled as" is unnecessary and confusing. If it's the PR title then we can change it. 
Furthermore, I was looking through the order and I don't understand to why some of them are incorrectly labelled. For example, dsn_class v.0.2.7 was in August 7-13 while dsn_class v.0.2.8 was in August 14-20, but was said to be incorrectly labelled as v.0.2.8 (it should be correct, unless I'm missing something)?

Another inconsistency is sometimes the files are named dsn_levels.txt and dsn_class.txt, when they're .py files.

I also think that it would be better to include the PR number (#nn) to better see which reference we're talking about (since the changes were done in date ranges)

**Comment by shoc71** [comment]
These are all good points and I have opened up an issue for this. I plan on fixing all of this by the end of next week Sunday. I don't plan on reworking it now. 

> I think the "incorrectly labelled as" is unnecessary and confusing. If it's the PR title then we can change it. Furthermore, I was looking through the order and I don't understand to why some of them are incorrectly labelled. For example, dsn_class v.0.2.7 was in August 7-13 while dsn_class v.0.2.8 was in August 14-20, but was said to be incorrectly labelled as v.0.2.8 (it should be correct, unless I'm missing something)?

There were a few instances of repetition, mislabelling, and skipping names that needed to be addressed (especially since they are not following the order system we had in place), hence why I added the "incorrectly labeled as". Also, I couldn't tell the difference between fixes and actual file updates without it being in the title, so we need to clear that up. How does a fix differentiate from a normal update to the code?
 
> Another inconsistency is sometimes the files are named dsn_levels.txt and dsn_class.txt, when they're .py files.

That's an easy fix for next week to make things more consistent. 

> I also think that it would be better to include the PR number (#nn) to better see which reference we're talking about (since the changes were done in date ranges)

Opened an issue up for this. This is a valid point as linking or copying the link will make going back to these instances of the code much more easier.

**Comment by shoc71** [comment]
For the time being, I think we should merge this regardless.

**Comment by slysnivy** [comment]
> These are all good points and I have opened up an issue for this. I plan on fixing all of this by the end of next week Sunday. I don't plan on reworking it now. 


No rush, these are a lot of changes and you did a good job 👍!


> especially since they are not following the order system we had in place), hence why I added the "incorrectly labeled as". 


Remember the comment I made on the update patch notes issue? We would acknowledge the change in naming from individual PR's and dsn_patches.


> Also, I couldn't tell the difference between fixes and actual file updates without it being in the title, so we need to clear that up. **How does a fix differentiate from a normal update to the code?**


Remember that fixes are to address bugs/oversights found soon after a major PR. They didn't deserve a new update name themselves as they were **only a few lines** different from the normal update.


> Also also, I don't think its worth going back through all those PRs just to fix the title just to make things more consistent. As there are numerous instances of misordering them, especially for levels.txt. I believe addressing them in patch-notes should be enough.


Well it makes it incredibly difficult for those who didn't do the update notes (including me) because it's too confusing. I had more luck just going through the old PR's themselves over using the updates.txt.

**Comment by shoc71** [comment]
> Remember that fixes are to address bugs/oversights found soon after a major PR. They didn't deserve a new update name themselves as they were only a few lines different from the normal update.

Thanks for the clarification. 

> Well it makes it incredibly difficult for those who didn't do the update notes (including me) because it's too confusing. I had more luck just going through the old PR's themselves over using the updates.txt.

Interesting... that's why I liked the idea of linking or using the PR_numbers to reference to them for it to make sense. Easier for everybody to read back and look at them.

**Comment by slysnivy** [comment]
> For the time being, I think we should merge this regardless. Makes things easier to edit and we have an updated document for now, we can always update this later.

I will close it then. Sorry I missed this comment lol

**Pull request merged**
